Update update-city-list-json.yml

diff --git a/.github/workflows/update-city-list-json.yml b/.github/workflows/update-city-list-json.yml
--- a/.github/workflows/update-city-list-json.yml
+++ b/.github/workflows/update-city-list-json.yml
@@ -14,17 +14,20 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Download and decompress gzipped file
+      shell: bash
       env:
         URL: ${{ secrets.CITY_LIST_JSON_URL }}
       run: |
-        wget -q ${URL}
-        gunzip city.list.min.json.gz
+        if wget -q ${URL} then;
+          gunzip city.list.min.json.gz
+        else
+          echo "ERROR: Cannot download city JSON file." && exit 1
+        fi
 
     - name: Rename and Move JSON file to public/assets Directory
       run: |
-        mv city.list.min.json city_list.json
-        mv city_list.json public/assets/
-
+        mv city.list.min.json public/assets/city_list.json
+        
     - name: Set Git user config
       run: |
         git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
